# -*- coding: utf-8 -*-
"""CNN_Pedestrian_Detection_Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K75KjdeflkWszNlETbbT5kklue7Ox1Jh
"""

import torch
import torchvision
import cv2
import numpy as np
import matplotlib.pyplot as plt

print("Torch version:", torch.__version__)
print("Torchvision version:", torchvision.__version__)
print("Setup successful")

from google.colab import files
uploaded = files.upload()

import torch
import torchvision
from torchvision import transforms
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Load pre-trained Faster R-CNN model
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval()

# Load image
image = Image.open("ped.jpg").convert("RGB")

# Transform image
transform = transforms.ToTensor()
img = transform(image)

# Run model
with torch.no_grad():
    predictions = model([img])

# Get results
boxes = predictions[0]['boxes']
labels = predictions[0]['labels']
scores = predictions[0]['scores']

# Plot image
fig, ax = plt.subplots(1, figsize=(10, 8))
ax.imshow(image)

person_found = False

# Draw boxes
for i in range(len(boxes)):
    if labels[i] == 1 and scores[i] > 0.5:  # 1 = person
        person_found = True
        box = boxes[i].numpy()
        x1, y1, x2, y2 = box

        rect = patches.Rectangle(
            (x1, y1),
            x2 - x1,
            y2 - y1,
            linewidth=2,
            edgecolor='green',
            facecolor='none'
        )
        ax.add_patch(rect)

        ax.text(x1, y1, f'Person: {scores[i]:.2f}',
                color='green', fontsize=10)

if not person_found:
    print("No person detected.")

plt.axis('off')
plt.show()

from google.colab import files
uploaded = files.upload()

import torch
import torchvision
from torchvision import transforms
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Load pre-trained Faster R-CNN model
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval()

# Load image
image = Image.open("pedistrain.png").convert("RGB")

# Transform image
transform = transforms.ToTensor()
img = transform(image)

# Run model
with torch.no_grad():
    predictions = model([img])

# Get results
boxes = predictions[0]['boxes']
labels = predictions[0]['labels']
scores = predictions[0]['scores']

# Plot image
fig, ax = plt.subplots(1, figsize=(10, 8))
ax.imshow(image)

person_found = False

# Draw boxes
for i in range(len(boxes)):
    if labels[i] == 1 and scores[i] > 0.5:  # 1 = person
        person_found = True
        box = boxes[i].numpy()
        x1, y1, x2, y2 = box

        rect = patches.Rectangle(
            (x1, y1),
            x2 - x1,
            y2 - y1,
            linewidth=2,
            edgecolor='green',
            facecolor='none'
        )
        ax.add_patch(rect)

        ax.text(x1, y1, f'Person: {scores[i]:.2f}',
                color='green', fontsize=10)

if not person_found:
    print("No person detected.")

plt.axis('off')
plt.show()

import torch
import torchvision
from torchvision import transforms
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Load pre-trained Faster R-CNN model
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval()

# Load image
image = Image.open("pedistrain.png").convert("RGB")

# Transform image
transform = transforms.ToTensor()
img = transform(image)

# Run model
with torch.no_grad():
    predictions = model([img])

boxes = predictions[0]['boxes']
labels = predictions[0]['labels']
scores = predictions[0]['scores']

fig, ax = plt.subplots(1, figsize=(12, 8))
ax.imshow(image)

for i in range(len(boxes)):
    if labels[i] == 1 and scores[i] > 0.5:
        box = boxes[i].numpy()
        x1, y1, x2, y2 = box

        rect = patches.Rectangle(
            (x1, y1),
            x2 - x1,
            y2 - y1,
            linewidth=2,
            edgecolor='green',
            facecolor='none'
        )
        ax.add_patch(rect)

        ax.text(x1, y1, f'Person: {scores[i]:.2f}',
                color='green', fontsize=10,
                bbox=dict(facecolor='white', alpha=0.7, edgecolor='none'))

plt.axis('off')
plt.savefig("detected_output.png", bbox_inches='tight', pad_inches=0.1)
plt.show()

print("Saved as detected_output.png")

person_count = 0
confidences = []

for i in range(len(boxes)):
    if labels[i] == 1 and scores[i] > 0.5:
        person_count += 1
        confidences.append(scores[i].item())

print("Total persons detected:", person_count)
print("Confidence scores:", confidences)

import time

start = time.time()

with torch.no_grad():
    predictions = model([img])

end = time.time()

fps = 1 / (end - start)

print("FPS:", fps)